document.writeln("  <!-- Mobile version footer -->");
document.writeln("    <div id=\'footer_mobile\'>");
document.writeln("        <div class=\'footer_mobile\'>");
document.writeln("            <ul>");
document.writeln("                <li>Store</li>");
document.writeln("                <li>Customer Service</li>");
document.writeln("                <li>Account</li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <div class=\'footer_buttom\'>");
document.writeln("            <div class=\'footer_icon\'>");
document.writeln("                <img src=\'../images/instagram-mobile.png\' alt=\'instagram-mobile\'>");
document.writeln("                <img src=\'../images/facebook-mobile.png\' alt=\'facebook-mobile\'>");
document.writeln("                <img src=\'../images/twitter-mobile.png\' alt=\'twitter-mobile\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'subscribe_mobile\'>");
document.writeln("                <span>Get all the news, subscribe to our newsletter</span>");
document.writeln("                <div class=\'subscribe_box_mobile\'>");
document.writeln("                    <input type=\'text\' placeholder=\'Email Address\'>");
document.writeln("                    <button>subscribe</button>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("    <!-- Desktop version footer -->");
document.writeln("    <div class=\'footer_desktop\'>");
document.writeln("        <ul>");
document.writeln("            <li>Store</li>");
document.writeln("    <a href=\'product_listing.html\'><li>All Games</li></a>");
document.writeln("            <li>Preorder Now</li>");
document.writeln("            <li>Board Game</li>");
document.writeln("            <li>Dice Game</li>");
document.writeln("            <li>Card Game</li>");
document.writeln("            <li>Puzzle</li>");
document.writeln("            <li>Role Playing Game</li>");
document.writeln("            <li>Family Game</li>");
document.writeln("            <li>Magic Singles</li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <li>Customer Service</li>");
document.writeln("            <li class=\'service\'>About Us</li>");
document.writeln("            <li class=\'service\'>Contact</li>");
document.writeln("            <li class=\'service\'>Gift Voucher</li>");
document.writeln("            <li class=\'service\'>Instagram</li>");
document.writeln("            <li class=\'service\'>Facebook</li>");
document.writeln("            <li class=\'service\'>Twitter</li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("            <li>Account</li>");
document.writeln("            <li>Log In</li>");
document.writeln("            <li>Sign Up</li>");
document.writeln("        </ul>");
document.writeln("");
document.writeln("        <div class=\'Subscribe\'>");
document.writeln("            <span>Get all the news, subscribe to our newsletter</span>");
document.writeln("            <div class=\'subscribe_box\'>");
document.writeln("                <input type=\'text\' placeholder=\'Email Address\'>");
document.writeln("                <button>subscribe</button>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");