document.writeln(" <!-- Mobile version header -->");
document.writeln("    <header id=\'mobile_version_header\'>");
document.writeln("        <div>");
document.writeln("            <img src=\'../images/menu.png\' alt=\'menu\' id=\'m\'>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("<a href=\'homepage.html\'><img src=\'../images/logo.png\' alt=\'logo\'></a>");
document.writeln("            ");
document.writeln("        </div>");
document.writeln("        <div class=\'top_icon\'>");
document.writeln("            <div class=\'left-side\'>");
document.writeln("<ul class=\'left-two\'>");
document.writeln("                    <li>");
document.writeln("<a href=\'account_login.html\'><img src=\'../images/account.png\' alt=\'account\'></a>");
document.writeln("                        ");
document.writeln("                    </li>");
document.writeln("                    <li id=\'shopping_cart_button\'>");
document.writeln("<a href=\'shopping_cart.html\'><img src=\'../images/shopping-cart.png\' alt=\'shopping-cart\'></a>");
document.writeln("                        ");
document.writeln("                    </li>");
document.writeln("                    </ui>");
document.writeln("            </div>");
document.writeln("            <div class=\'right-side\'>");
document.writeln("<img src=\'../images/search.png\' alt=\'search\' id=\'searchs\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");
document.writeln("");
document.writeln("    <!-- Desktop version header -->");
document.writeln("    <div id=\'Desktop_version_header\'>");
document.writeln("        <div>");
document.writeln("            <a class=\'a\' href=\'homepage.html\'><img class=\'nav_logo\' src=\'../images/logo.png\' alt=\'logo\'></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'search\'>");
document.writeln("            <a href=\'search_results.html\' class=\'search_bar\'></a><input type=\'text\' placeholder=\'Search...\'>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("            <ul class=\'nav_list_left\'>");
document.writeln("                <li><a href=\'product_listing.html\'>Store</a></li>");
document.writeln("                <li><a href=\'about.html\'>About</a></li>");
document.writeln("                <li><a href=\'contact.html\'>Contact</a></li>");
document.writeln("            </ul>");
document.writeln("            <ul class=\'nav_list\'>");
document.writeln("                <li><a href=\'wishlist.html\'>Wishlist</a></li>");
document.writeln("                <li><a href=\'account_login.html\'>Account</a></li>");
document.writeln("                <li><a href=\'shopping_cart.html\'>Cart</a></li>");
document.writeln("            </ul>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("");

document.writeln("<div id=\'m_list\'>");
document.writeln("        <img id=\'close\' src=\'../images/close-mobile.png\' alt=\'close\'>");
document.writeln("        <ul>");
document.writeln("            <a style=\'color: inherit;\' href=\'#\'>");
document.writeln("                <li id=\'store\'>Store&nbsp;&nbsp;<i style=\'font-style: normal;\' id=\'jiahao\'>+</i></a>");
document.writeln("            <ul class=\'open\' id=\'open\'>");
document.writeln("                <a style=\'color: inherit;\' href=\'product_listing.html\'>");
document.writeln("                    <li>All Games</li>");
document.writeln("                </a>");
document.writeln("                <li>Preorder</li>");
document.writeln("                <li>Board Games</li>");
document.writeln("                <li>Dice Games</li>");
document.writeln("                <li>Card Games</li>");
document.writeln("                <li>Puzzles</li>");
document.writeln("                <li>Role Playing Game</li>");
document.writeln("                <li>Family</li>");
document.writeln("                <li>Magic Singles</li>");
document.writeln("            </ul>");
document.writeln("            </li>");
document.writeln("            <a style=\'color: inherit;\' href=\'about.html\'>");
document.writeln("                <li>About</li>");
document.writeln("            </a>");
document.writeln("            <a style=\'color: inherit;\' href=\'contact.html\'>");
document.writeln("                <li>Contact</li>");
document.writeln("            </a>");
document.writeln("            <a style=\'color: inherit;\' href=\'Wishlist.html\'>");
document.writeln("                <li>Wishlist</li>");
document.writeln("            </a>");
document.writeln("        </ul>");
document.writeln("    </div>");


document.writeln(" <div class=\'search_f\' id=\'search_f\'>");
document.writeln("        <i style=\'display: none;\' id=\'test2\'>1</i>");
document.writeln("        <input class=\'searchz\' placeholder=\'horror\'>");
document.writeln("    <a href=\'search_results.html\'><img src=\'../images/search-mobile.png\' alt=\'\' id=\'search-mobile\'></a>    ");
document.writeln("    </div>");