document.writeln("  <!-- Mobile version header -->");
document.writeln("    <header id=\'mobile_version_header\'>");
document.writeln("        <div>");
document.writeln("            <img src=\'../images/menu.png\' alt=\'menu\' id=\'m\'>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("<a href=\'homepage.html\'><img src=\'../images/logo.png\' alt=\'logo\'></a>");
document.writeln("            ");
document.writeln("        </div>");
document.writeln("        <div class=\'top_icon\'>");
document.writeln("            <div class=\'left-side\'>");
document.writeln("<ul class=\'left-two\'>");
document.writeln("                    <li>");
document.writeln("<a href=\'account_login.html\'><img src=\'../images/account.png\' alt=\'account\'></a>");
document.writeln("                        ");
document.writeln("                    </li>");
document.writeln("                    <li id=\'shopping_cart_button\'>");
document.writeln("<a href=\'shopping_cart.html\'><img src=\'../images/shopping-cart.png\' alt=\'shopping-cart\'></a>");
document.writeln("                        ");
document.writeln("                    </li>");
document.writeln("                    </ui>");
document.writeln("            </div>");
document.writeln("            <div class=\'right-side\'>");
document.writeln("                <img src=\'../images/search.png\' alt=\'search\' id=\'searchs\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");
document.writeln("    <!-- Desktop version header -->");
document.writeln("    <div id=\'Desktop_version_header\'>");
document.writeln("        <div>");
document.writeln("            <a class=\'a\' href=\'homepage.html\'><img class=\'nav_logo\' src=\'../images/logo.png\' alt=\'logo\'></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'search\'>");
document.writeln("            <a href=\'search_results.html\' class=\'search_bar\'></a><input type=\'text\' placeholder=\'Search...\'>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("            <ul class=\'nav_list\'>");
document.writeln("                <li><a href=\'wishlist.html\'>Wishlist</a></li>");
document.writeln("                <li><a href=\'account_login.html\'>Account</a></li>");
document.writeln("                <li><a href=\'shopping_cart.html\'>Cart</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");